### DISCUSSION TITLE
Is automating charge / de-charge for a heat pump a good or a bad idea?

### DISCUSSION THREAD

**Discussion by krausest** [weltmeyer/ha_sonnenbatterie#102] [General]
I built an automation that should optimize the PV usage for my heat pump in the morning. Often the sun shines, but the PV power is used to charge the battery. If we would adjusting loading the battery to a value such that the heat pump's power is fed into the grid, the PV would actually load the heat pump (as measured by a cascaded connection).

Example:
PV produces 1.200 Watts,
Home consumes 200 Watts,
heat pump consumes 700 Watts,
then battery charge should be 300 Watts.

If some conditions match (PV produces enough power, battery isn't completely empty, the solar forecast for today looks good and the heat pump is running) I change the sonnenbattery to manual mode.
I'm adjusting the charge or de-charge of the battery similarly to the example above every 10 seconds as long as the heat pump is running.
After that the sonnenbattery is set back to automatic mode.

**Any opinions? Does setting the charge / de-charge level every 10 seconds sound acceptable or would you fear damaging the battery?**

(If interested I can show the full automation. I'm not an expert in HA automation so it might not be as efficient as possible. I'm using a timer and listening to timer events which might be a bit convoluted, but I managed to get a solid understanding of the state of the automation).

**Comment by RustyDust** [comment]
I guess I know what you intention is, but first I have a different question just for my understanding:
Your heat pump seems not to be wired into your home as electrical load but instead seems to runs as a separate load? Why? And how do you measure  the consumption of the heat pump (and your home)?

As to your other questions (also from he closed ticket):
- Yes, Sonnen did a firmware update, mainly to facilitate the new Auto-Optimizing functionality in the "sonnen" App (not to be confused with the older "'my sonnen" app). This comes with a new operating mode (11) and maybe some other changes.
- (Re-)setting the amount of charged/decharged power every 10 seconds shouldn't really damage the SonnenBatterie from a software point of view but unreality that largely depends on how this is handled internally by the SonnenBatterie. If those values are stored in NVRAM with a limited amount of write cycles you're obviously wearing down the life span of that NVRAM. Also you have to keep in mind that all values you read from the SonnenBatterie are already outdated the very moment you read them since the consumption of every electrical load fluctuates 50 times a second. So all you get is a rough approximation - or maybe better: a snapshot in time of the value you queried. So instead of adjusting this every 10 seconds I'd rather use a more generalised approach: I'd define appropriate margins like for example 50 or 100W. Then when reading the consumption of the heat pump I'd look whether the current value is within the frame of `[last-read-value - margin, last-read-value + margin]` and if it is, I wouldn't change the SonnenBatterie's setting but just live with the slight inaccuracy.

And lastly, yes, the automation might help to fully understand your intention, along with a rough wiring scheme of your setup.

**Comment by krausest** [comment]
Thanks for your reply. The wiring scheme is a "Kaskadenschaltung" as described here: https://blog.naturstrom.de/energiewende/kaskadenschaltung/

There are two electricity meters involved: An outer meter and an inner meter. 
```
Grid <--> Outer electricity meter <--> Heat pump <--> Inner electricity meter <--> battery, pv, home electricity
```
This setup seems to be necessary to get a lower rate for the heat pump power. Each meter counts the energy consumed and produced.
The purchased amount of energy for the heat pump ist then: grid-in power (or whatever "Bezug" means in English) from the outer meter minus grid-in power from the inner meter.
The total consumption of the heat pump is the purchased amount plus grid-out power ("Einspeisung") from the inner minus grid-out power of the outer. This adds the self produced PV that the battery sent to the grid but was consumed by the heat pump.

I'm measuring the heat pump consumption with a shelly EM 3 Pro. The sonnenbatterie measures the home consumption but does not include the heat pump.

My goal is to delay or pause loading the battery in the morning when the heat pump is running (at least on sunny days). I haven't found an easy way to achieve that goal. Quite the opposite: When I set a charge target, then the battery won't discharge when needed (home power > pv production). Ideally I could set some target value for the grid feed-in for the battery. I'm trying to compute this value in the automation now.

I'm decomposing the automation in five simpler automations:

1. Between 6:00 and 10:00 check all 5 minutes if:
   1. The heat pump optimization isn't currently running
   2. Heat pump is running
   1. The battery is above 5%
   2. PV production is above 1500 W
   3. Remaining forecast for solar production for today is more than 10 kWh
   If so start the optimization timer for two hours (the heat pump optimization is running when the timer is active).
2. When the start or restart event for the optimization timer fires then set the operation mode of the sonnenbattery to manual
3. Every 10th second when the timer is running compute:
    * charge target "Ladeziel": max(0, PV power (from sonnenbattery) - heat pump power - home consumption (from sonnenbattery)). This is the amount of power that still could be charged such that the PV feeds in the consumption of the heat pump. 
    * discharge target "Entladeziel": max(0, home consumption - PV power). This is only positive in situation when the home consumption is larger than the PV production and when the battery should be used to satisfy the power request. 
   If the discharge target "Entladeziel" is > 0 discharge_battery for the de-charge target
   Else charge_battery for the charge target
4. Stop the optimization timer if the heat pump power consumption is below 100 W
5. When the finish, cancel or pause event for the optimization timer fires, set operation mode to automatic again. 

This might seem a bit rough, but it allows me to start and stop the optimization manually (by starting or stopping the timer), I can display the values for the charge and discharge target and look at the traces.
Power consumption varies of course but a short spike isn't relevant for me. I had the automation running a few times (before the error from the other discussion happened) and saw on the electricity meters that I could indeed squeeze a few kWh of self produced power for the heat pump.

Here's the yaml code:

Automation 1 
```yaml
alias: "WP+PV 1: Laden der Batterie wg. Wärmepumpe anpassen (Timer start)"
description: ""
triggers:
  - minutes: /5
    trigger: time_pattern
    hours: "6"
  - minutes: /5
    trigger: time_pattern
    hours: "7"
  - minutes: /5
    trigger: time_pattern
    hours: "8"
  - minutes: /5
    trigger: time_pattern
    hours: "9"
conditions:
  - condition: state
    entity_id: timer.resetbatterysuspend
    state: idle
  - condition: numeric_state
    entity_id: sensor.shellypro3em_34987a46a2a4_total_active_power
    above: 100
  - condition: numeric_state
    entity_id: sensor.sonnenbatterie_218665_state_battery_percentage_real
    above: 5
  - condition: numeric_state
    entity_id: sensor.sonnenbatterie_218665_state_production
    above: 1500
  - condition: numeric_state
    entity_id: sensor.energy_production_today_remaining
    above: 10
actions:
  - action: persistent_notification.create
    metadata: {}
    data:
      message: "WP+PV 1: Laden der Batterie wg. Wärmepumpe anpassen (Timer start)"
  - action: timer.start
    metadata: {}
    data: {}
    target:
      entity_id: timer.resetbatterysuspend
mode: single
```

Automation 2
```yaml
alias: >-
  WP+PV 2: Batterie in manuellen Modus setzen (Start 2. Timer.start => Batterie
  Manuell)
description: ""
triggers:
  - trigger: event
    event_type: timer.started
    event_data:
      entity_id: timer.resetbatterysuspend
  - trigger: event
    event_type: timer.restarted
    event_data:
      entity_id: timer.resetbatterysuspend
conditions: []
actions:
  - action: persistent_notification.create
    metadata: {}
    data:
      message: >-
        WP+PV 2: Batterie in manuellen Modus setzen (Start 2. Timer.start =>
        Batterie Manuell)
  - device_id: eb3a5ae6551232cc916e0691dca9bc81
    domain: select
    entity_id: 1a7987114a2508acc42b67ed42afda70
    type: select_option
    option: manual
    enabled: true
mode: single

```

Automation 3
```yaml
alias: "WP+PV 3: Batterieladung an WP-Verbrauch anpassen (Während)"
description: ""
triggers:
  - trigger: time_pattern
    seconds: /10
    hours: "6"
    minutes: "*"
  - trigger: time_pattern
    seconds: /10
    hours: "7"
    minutes: "*"
  - trigger: time_pattern
    seconds: /10
    hours: "8"
    minutes: "*"
  - trigger: time_pattern
    seconds: /10
    hours: "9"
    minutes: "*"
  - trigger: time_pattern
    seconds: /10
    hours: "10"
    minutes: "*"
  - trigger: time_pattern
    seconds: /10
    hours: "11"
    minutes: "*"
  - trigger: time_pattern
    seconds: /10
    hours: "12"
    minutes: "*"
conditions:
  - condition: state
    entity_id: timer.resetbatterysuspend
    state: active
    enabled: true
actions:
  - action: input_number.set_value
    metadata: {}
    data_template:
      value: >-
        {{ min(3400, max(0,
        (states('sensor.sonnenbatterie_218665_state_production')| float(0))  -
                  (states('sensor.shellypro3em_34987a46a2a4_total_active_power')| float(0)) -
                  (states('sensor.sonnenbatterie_218665_state_consumption_current')| float(0))              
              )) }}
    target:
      entity_id: input_number.wp_pv_ladeziel
  - action: input_number.set_value
    metadata: {}
    data_template:
      value: >-
        {{  min(3400, max(0,
        (states('sensor.sonnenbatterie_218665_state_consumption_current')|
        float(0))  -
                  (states('sensor.sonnenbatterie_218665_state_production')| float(0))              
              )) }}
    target:
      entity_id: input_number.wp_pv_entladeziel
  - if:
      - condition: numeric_state
        entity_id: input_number.wp_pv_entladeziel
        above: 0
    then:
      - action: number.set_value
        metadata: {}
        data:
          value: "{{states('input_number.wp_pv_entladeziel')|float(0)}}"
        target:
          entity_id: number.sonnenbatterie_218665_number_discharge
        enabled: true
    else:
      - action: number.set_value
        metadata: {}
        data:
          value: "{{states('input_number.wp_pv_ladeziel')|float(0)}}"
        target:
          entity_id: number.sonnenbatterie_218665_number_charge
mode: single

```


Automation 4
```yaml
alias: "WP+PV 4: Timer beenden wenn WP aus (Stop 1)"
description: ""
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.vvm500_pumpe_zustand_trigger
    from: null
    to: "off"
    enabled: true
  - trigger: numeric_state
    entity_id:
      - sensor.shellypro3em_34987a46a2a4_total_active_power
    below: 100
    enabled: true
conditions:
  - condition: state
    entity_id: timer.resetbatterysuspend
    state: active
actions:
  - action: notify.persistent_notification
    metadata: {}
    data:
      message: "WP+PV 4: Timer beenden wenn WP aus (Stop 1)"
  - action: timer.finish
    metadata: {}
    data: {}
    target:
      entity_id: timer.resetbatterysuspend
mode: single
```


Automation 5 
```yaml
alias: >-
  WP+PV 5: Batterie wieder laden (Stop 2. Timer.finished => Automatikmodus
  Batterie)
description: ""
triggers:
  - trigger: event
    event_type: timer.finished
    event_data:
      entity_id: timer.resetbatterysuspend
  - trigger: event
    event_type: timer.cancelled
    event_data:
      entity_id: timer.resetbatterysuspend
  - trigger: event
    event_type: timer.paused
    event_data:
      entity_id: timer.resetbatterysuspend
conditions: []
actions:
  - action: notify.persistent_notification
    metadata: {}
    data:
      message: >-
        WP+PV 5: Batterie wieder laden (Stop 2. Timer.finished => Automatikmodus
        Batterie)
  - action: input_number.set_value
    metadata: {}
    data:
      value: 0
    target:
      entity_id:
        - input_number.wp_pv_ladeziel
        - input_number.wp_pv_entladeziel
  - device_id: eb3a5ae6551232cc916e0691dca9bc81
    domain: select
    entity_id: 1a7987114a2508acc42b67ed42afda70
    type: select_option
    option: automatic
    enabled: true
mode: single

```
