### ISSUE TITLE
Service to set Sonnenbatterie to charge fails

### ISSUE THREAD

**Issue by dieterxy** [weltmeyer/ha_sonnenbatterie#78]
The action to set the Sonnenbatterie to charge mode:

``` yaml
action: sonnenbatterie.charge_battery
data:
  power: 1000
  device_id: a3f19a327de5f534500fbb4bdc888eb4
```

leads to the following error:

```
Failed to perform the action sonnenbatterie.charge_battery. invalid value or type (must have a partial ordering) for dictionary value @ data['power']. Got None
```

It already worked some time ago. I have the impression that the problem came with the v2025.01.02 version.
Setting the mode from the dashboard works.

Entries in the log:

```
Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/script.py:2041
First occurred: 11:36:49 AM (4 occurrences)
Last logged: 12:08:53 PM

websocket_api script: Error executing script. Invalid data for call_service at pos 1: invalid value or type (must have a partial ordering) for dictionary value @ data['power']
```
