### ISSUE TITLE
Error from set_tou_schedule

### ISSUE THREAD

**Issue by GrumpyBusted** [weltmeyer/ha_sonnenbatterie#89]
After updating to 2025.02.02 I get "Error: list indices must be integers or slices, not str" from 
action: sonnenbatterie.set_tou_schedule
data:
  device_id: XXXXXXXXXXXX
  schedule:
    - start: '00:00'
      stop: '06:00'
      threshold_p_max: 8480
    - start: '06:01'
      stop: '17:00'
      threshold_p_max: 0

This worked before

**Comment by RustyDust** [comment]
I actually wonder why this has supposedly worked before, for the correct syntax would be

``` yaml
action: sonnenbatterie.set_tou_schedule
data:
  device_id: redacted
  schedule: >-
    { [ "start": "00:00", "stop": "06:00", "threshold_p_max": 8480 ], 
      [ "start": "06:01", "stop": "17:00", "threshold_p_max": 0 ]}
```

See also here: https://github.com/weltmeyer/ha_sonnenbatterie#set_tou_schedulescheduleschedule_array

**Comment by GrumpyBusted** [comment]
Thanks for your input, I believe it should be an array with objects, not object with arrays, like below.

I have tried both my own data, and the sample data from the link, but none of them work, the both give "Failed to perform the action sonnenbatterie.set_tou_schedule. Unknown error"

```
action: sonnenbatterie.set_tou_schedule
data:
  device_id: xxxxxxxxxxx
  schedule: >-
    [ { "start": "00:00", "stop": "06:00", "threshold_p_max": 8480 }, 
      { "start": "06:01", "stop": "17:00", "threshold_p_max": 0 } ]    
response_variable: conversation_response
```

```
action: sonnenbatterie.set_tou_schedule
data:
  device_id: xxxxxxxxxxxxx
  schedule: '[{"start":"10:00", "stop":"10:00", "threshold_p_max": 2000}]'
response_variable: conversation_response
```

I have checked the logs, nothing to see there.
