### ISSUE TITLE
Setting values for sonnenbatterie.discharge_battery does not function as part of a script

### ISSUE THREAD

**Issue by Telefonmann2022** [weltmeyer/ha_sonnenbatterie#95]
Hi,

I am very new to GitHub, so I hope I’m not violating any netiquette with this post. Also, I'm not sure if this issue is due to the integration itself or because of my own lack of experience with YAML, scripting, etc. I've spent several hours trying to figure it out and would really appreciate some help. I suspect others might face the same issue.

I’ve integrated my Sonnenbatterie with Home Assistant using this really great integration, and it works really well for monitoring. It also works for manually setting charge and discharge values in 100-Watt increments.

Now, I’d like to set these values dynamically based on another sensor. Specifically, I want the battery to discharge as much as the watt meter measures. This is because the Sonnen system always consumes some energy (~30-50 Watts) from the grid, even when it’s full.

I’ve created this action, but unfortunately, I’m getting an error message.

```
action: sonnenbatterie.discharge_battery
metadata: {}
data:
  device_id: 9dd8738eea23bd439542f07a7ea9xxxx
  power: "{{ states('sensor.sonnenbatterie_149477_state_consumption_current') }}"
```
Error: expected str for dictionary value @ data['power']. Got None
